### ISSUE TITLE
Fehler mit TVBrowser

### ISSUE THREAD

**Issue by ghbw** [GollmerSt/TimerImportTool#1]
Hi, danke für das Tool, dass das die Senderzuordnung und das Aufzeichnen von Sendungen mit dem TVBrowser wesentlich vereinfacht.

Ich bekomme vom TVBrowser gelegentlich folgende Fehlermedlung:
![grafik](https://user-images.githubusercontent.com/77881682/105578845-58644f80-5d83-11eb-9687-46fac0ea2a5d.png)

Mir fiel auf, dass wenn ich diese Fehlermeldung erhalte, ich auch keine Aufnahmen im TVBrowser direkt von Hand anlegen konnte.
Wenn ich die Verbindung zum Recording Service von Hand in der Plugin-Verwaltung des TVBrowsers wieder initiiere funktioniert wieder alles wie gewohnt.

Woran könnte es liegen?

Viele Grüße

**Comment by GollmerSt** [comment]
Hallo,

Danke für den Hinweis.

Das Tool ist sowohl als TVBrowser-Plugin als auch als Standalone-Version lauffähig. Beim Kompilieren benötige ich daher eine abgespeckte TVBrowser-Library. Leider hatte diese einen Fehler in einer Definition, so dasss es zu diesem ungewöhnlichenh Fehler kam.

In der Version 1.04.04 sollte der Fehler gefixt sein.

Viele Grüße
     Stefan
